language: csharp
script:
  - xbuild /p:Configuration=Debug Test.sln
before_install:
  - sudo nuget install -OutputDirectory packages NUnit -Version 3.7.1
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Test.sln
after_script:
  - nunit-console bin/Debug/Test.dll
